baseURL = "http://dev.andytough.com/"
languageCode = "en"
title = "Andy Tough"
#theme = "hyde"
theme = "at-minimal"
#publishDir = "/Users/andy/Desktop/pub"
#archetypeDir = "themes/at-minimal/archetypes"

[params]
description = "Andy Tough Hugo Site hp"
author = "Andy Tough hp"
copyrightstartdate = "2001"
copyright = "Andy Tough. All Rights Reserved."
sectionPagesMenu = "main"

