baseURL = "https://dev.andytough.com/"
languageCode = "en"
title = "Andy Tough"
theme = "at-minimal"
#archetypeDir = "themes/at-minimal/archetypes"
googleAnalytics = "UA-8414026-7"
#publishDir = "/Users/andy/Desktop/HugoPublish"

[params]
description = "Andy Tough Hugo Site hp"
author = "Andy Tough hp"
copyrightstartdate = "2001"
copyright = "Andy Tough. All Rights Reserved."
sectionPagesMenu = "main"

[menu]
[[menu.main]]
    identifier = "introduction"
    name = "Introduction"
    title = "Introduction"
    url = "/"
    weight = 1

[[menu.main]]
    identifier = "testimonials"
    name = "Testimonials"
    title = "Testimonials"
    url = "/testimonials/"
    weight = 5

[[menu.main]]
    identifier = "clients"
    name = "Clients"
    title = "Clients"
    url = "/clients/"
    weight = 10

[[menu.main]]
    identifier = "gallery"
    name = "Gallery"
    title = "Gallery"
    url = "/gallery/"
    weight = 11

[[menu.main]]
    identifier = "articles"
    name = "Articles"
    title = "Articles"
    url = "/articles/"
    weight = 15

[[menu.main]]
    identifier = "contact"
    name = "Contact"
    title = "Contact Me"
    url = "/contact/"
    weight = 20
    
[sitemap]
  changefreq = "monthly"
  filename = "sitemap.xml"
  priority = 0.5