baseURL = "https://dev.andytough.com/"
languageCode = "en"
title = "Andy Tough"
theme = "at-minimal"
#archetypeDir = "themes/at-minimal/archetypes"

[params]
description = "Andy Tough Hugo Site hp"
author = "Andy Tough hp"
copyrightstartdate = "2001"
copyright = "Andy Tough. All Rights Reserved."
sectionPagesMenu = "main"

